services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/encurtador_db?authSource=admin
      - APP_BASE_URL=http://localhost:8080
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: