version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-encurtador
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - encurtador-network

volumes:
  mongodb_data:

networks:
  encurtador-network:
    driver: bridge