info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  main:
    lazy-initialization: false
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/encurtador_db?authSource=admin}
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    filter: true
    configUrl: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs
    enabled: true
    path: swagger-ui.html
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
    docExpansion: list
    syntax-highlight:
      activated: true